# Generated by Django 4.1.7 on 2023-08-02 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_orders"),
    ]

    operations = [
        migrations.RenameModel(old_name="Orders", new_name="Order",),
    ]
