# Generated by Django 4.1.7 on 2023-08-02 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_rename_orders_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="phone",
            field=models.CharField(default="", max_length=13),
        ),
    ]
