# Generated by Django 4.1.7 on 2023-08-08 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0008_order_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order", name="amount", field=models.IntegerField(default=0),
        ),
    ]
